# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170416_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text1',
            new_name='choice_text',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='question1',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='votes1',
            new_name='votes',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='pub_date1',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question1_text',
            new_name='question_text',
        ),
    ]
